-- ═══════════════════════════════════════════════════════════════════════════
-- DATOS INICIALES
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. SCHEDULES (Horarios de funcionamiento)
INSERT INTO schedules (day_of_week, opening_time, closing_time, is_open) VALUES
('MONDAY', '11:00', '22:00', true),
('TUESDAY', '11:00', '22:00', true),
('WEDNESDAY', '11:00', '22:00', true),
('THURSDAY', '11:00', '22:00', true),
('FRIDAY', '11:00', '23:00', true),
('SATURDAY', '12:00', '23:00', true),
('SUNDAY', '12:00', '22:00', true)
ON CONFLICT DO NOTHING;

-- 2. MENU CATEGORIES
INSERT INTO menu_categories (name, display_order, is_active) VALUES
('BEBIDAS', 1, true),
('COMIDAS', 2, true),
('POSTRES', 3, true),
('PROMOCIONES', 4, true)
ON CONFLICT DO NOTHING;

-- Get IDs for next inserts (will be filled during actual execution)
-- Note: These are placeholders - actual IDs will be auto-generated by UUIDs

-- 3. WAITERS (Meseros iniciales)
INSERT INTO waiters (waiter_code, full_name, phone, pin_code, is_active) VALUES
('MESERO-001', 'Carlos García', '3101234567', '$2b$10$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', true),
('MESERO-002', 'María López', '3109876543', '$2b$10$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', true),
('MESERO-003', 'Juan Rodríguez', '3105555555', '$2b$10$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', true)
ON CONFLICT DO NOTHING;

-- 4. TABLES (Mesas - 10 mesas totales)
INSERT INTO tables (table_number, capacity, zone, status) VALUES
('1', 2, 'Salón A', 'available'),
('2', 2, 'Salón A', 'available'),
('3', 4, 'Salón A', 'available'),
('4', 4, 'Salón A', 'available'),
('5', 2, 'Salón B', 'available'),
('6', 4, 'Salón B', 'available'),
('7', 6, 'Salón B', 'available'),
('VIP-1', 4, 'VIP', 'available'),
('VIP-2', 6, 'VIP', 'available'),
('BARRA-1', 2, 'Barra', 'available')
ON CONFLICT DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════════
-- NOTA: Los items de menú se cargarán después de crear las colecciones en Directus
-- Los datos de clientes se crearán dinámicamente durante pruebas
-- ═══════════════════════════════════════════════════════════════════════════
